services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-app
    container_name: chatbot-app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: db_helpdesk
    # ports:
    #   - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: db_helpdesk
      MYSQL_ROOT_PASSWORD: root
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
