services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-app
    container_name: chatbot-app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: db_helpdesk
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: db_helpdesk
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_EDITOR_BASE_URL: http://localhost:5678
      N8N_WEBHOOK_URL: http://localhost:5678
      N8N_ENDPOINT_WEBHOOK_CORS: http://localhost:8000
    volumes:
      - ~/.n8n:/home/node/.n8n

volumes:
  mysql_data:
